import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faGaugeHigh,
  faPercent,
  faArrowTrendUp,
  faArrowTrendDown,
  faCoins,
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUpRightFromSquare,
  faMinus,
  faMagnifyingGlass,
  faCheck,
  faTrophy,
  faCircleNotch,
  faCircleInfo,
  faEarthEurope,
  faSun,
  faMoon,
  faBuilding,
  faUser,
  faThumbsUp,
  faThumbsDown,
  faRobot,
  faCalendar,
  faSpinner,
  faRightToBracket,
  faRightFromBracket,
  faStar,
  faBookmark,
  faGem,
  faBullseye,
  faHandshake,
  faTriangleExclamation,
} from '@fortawesome/free-solid-svg-icons'
import { faStar as farStar } from '@fortawesome/free-regular-svg-icons'
import { faGoogle } from '@fortawesome/free-brands-svg-icons'
import type { App } from 'vue'

library.add(
  faGaugeHigh,
  faPercent,
  faArrowTrendUp,
  faArrowTrendDown,
  faCoins,
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUpRightFromSquare,
  faMinus,
  faMagnifyingGlass,
  faCheck,
  faTrophy,
  faCircleNotch,
  faCircleInfo,
  faEarthEurope,
  faSun,
  faMoon,
  faBuilding,
  faUser,
  faThumbsUp,
  faThumbsDown,
  faRobot,
  faCalendar,
  faSpinner,
  faRightToBracket,
  faRightFromBracket,
  faStar,
  faBookmark,
  faGem,
  faBullseye,
  faHandshake,
  faTriangleExclamation,
  farStar,
  faGoogle,
)

export function registerFontAwesome(app: App) {
  app.component('FontAwesomeIcon', FontAwesomeIcon)
}
